[package]
name = "rust_sdk"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
p256 = "0.12.0"
base64 = "0.22.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
hex = "0.4.3"
