[package]
name = "rust_sdk"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
p256 = { version = "0.12.0", default-features = false }
base64 = { version = "0.22.0", default-features = false }
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.115", default-features = false }
hex = { version = "0.4.3", default-features = false }
